Update benchmarks.yml

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -70,10 +70,10 @@ jobs:
       #   run: |
       #     bash setup.sh
           
-      - name: Wait For Connection
-        uses: google-ml-infra/actions/ci_connection@main
-        with:
-          halt-dispatch-input: ${{ inputs.halt-for-connection }}
+      # - name: Wait For Connection
+      #   uses: google-ml-infra/actions/ci_connection@main
+      #   with:
+      #     halt-dispatch-input: ${{ inputs.halt-for-connection }}
 
       # - name: Run run.sh for E2E benchmarks flax_2b (within venv)
       #   working-directory: xla/backends/cpu/benchmarks/e2e/gemma2/flax_2b
@@ -85,6 +85,45 @@ jobs:
       - name: Build run_hlo_module
         working-directory: xla
         run: bazel build -c opt --dynamic_mode=off //xla/tools:run_hlo_module
+
+      - name: Run HLO Module Benchmarks
+        working-directory: xla
+        continue-on-error: true
+        run: |
+          for file in xla/tests/fuzz/*.hlo; do
+            filename=$(basename "$file")
+            # Skip expected failed hlo files.
+            if [[ "$filename" == "rand_000060.hlo" || "$filename" == "rand_000067.hlo" || "$filename" == "rand_000072.hlo" ]]; then
+              echo "Skipping benchmark on $file"
+              continue
+            fi
+            echo "Running benchmark on $file"
+            ./bazel-bin/xla/tools/run_hlo_module --input_format=hlo --platform=CPU "$file"
+          done
+
+      - name: Build CPU Benchmarks
+        working-directory: xla
+        run: bazel build -c opt --dynamic_mode=off //xla/backends/cpu/benchmarks:*
+
+      - name: Run CPU benchmarks
+        working-directory: xla
+        continue-on-error: true
+        run: |
+          find ./bazel-bin/xla/backends/cpu/benchmarks/ -maxdepth 1 -type f -executable -name "*_test" -print0 | while IFS= read -r -d $'\0' benchmark; do
+            benchmark_name=$(basename "$benchmark" | sed 's/_test$//') 
+            echo "Running benchmark: $benchmark_name"
+
+            # Run the benchmark with default parameters.
+            $benchmark --benchmark_filter=".*"
+            $benchmark --benchmark_filter=".*" > "results/$benchmark_name.log" 2>&1
+
+            # Check the exit code of the benchmark
+            if [ $? -ne 0 ]; then
+              echo "Error: Benchmark '$benchmark_name' failed. Check the log file: results/$benchmark_name.log"
+            else
+              echo "Benchmark '$benchmark_name' completed successfully."
+            fi
+          done
 
 
       # - name: Wait For Connection
