Update benchmarks.yml

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -40,12 +40,11 @@ jobs:
 
       - name: Create results directory
         run: |
-          mkdir results
-          ls 
+          mkdir -p results
+          ls
 
       - name: Configure XLA for GPU backend
         run: |
-          ls
           ./configure.py --backend CUDA --nccl
 
       - name: Set TF_CPP_MAX_VLOG_LEVEL
@@ -56,51 +55,59 @@ jobs:
 
       - name: Build hlo_runner_main
         run: bazel build -c opt --config=cuda --dynamic_mode=off //xla/tools/multihost_hlo_runner:hlo_runner_main
-      - name: Wait For Connection
-        uses: google-ml-infra/actions/ci_connection@main
-        with:
-          halt-dispatch-input: ${{ inputs.halt-for-connection }}
-      # - name: Wait For Connection
-      #   uses: google-ml-infra/actions/ci_connection@main
-      #   with:
-      #     halt-dispatch-input: ${{ inputs.halt-for-connection }}
-     # TODO(juliagmt): Add more performance-criticalHLOs to benchmark.
-      - name: Run xla/tools/hlo_opt/tests/gpu_hlo_pass.hlo
+      
+      # TODO(juliagmt): Add more performance-criticalHLOs to benchmark.
+      - name: Run hlo_opt and generate xspace.pb
         run: |
-          ./bazel-bin/xla/tools/multihost_hlo_runner/hlo_runner_main --device_type=gpu --log_output=True --use_spmd_partitioning --xla_gpu_dump_xspace_to=results/xspace.pb xla/xla/tools/hlo_opt/tests/gpu_hlo_pass.hlo
+          WORKSPACE_DIR=$(pwd)
+          echo $WORKSPACE_DIR
+          ./bazel-bin/xla/tools/multihost_hlo_runner/hlo_runner_main --device_type=gpu --log_output=True --use_spmd_partitioning --xla_gpu_dump_xspace_to=$WORKSPACE_DIR/results/xspace.pb xla/tools/hlo_opt/tests/gpu_hlo_pass.hlo
+
+      - name: Verify xspace.pb creation
+        run: |
+          if [ -f results/xspace.pb ]; then
+            echo "xspace.pb successfully created."
+          else
+            echo "ERROR: xspace.pb was not created."
+            exit 1
+          fi
 
       - name: Set XSPACE_PATH
         env:
-          XSPACE_PATH: $(pwd)/results/xspace.pb
+          XSPACE_PATH: ${{ github.workspace }}/results/xspace.pb
         run: |
           echo "XSPACE_PATH is: $XSPACE_PATH"
+
       - name: Compute the cost of gpu_hlo_pass.hlo
         run: |
-          PWD=$(pwd)
-          bazel run //xla/tools:compute_cost -- --input=$PWD/xla/tools/hlo_opt/tests/gpu_hlo_pass.hlo --format=hlo --gpu
-            
+          if [ -f "$XSPACE_PATH" ]; then
+            bazel run //xla/tools:compute_cost -- --input=$PWD/xla/tools/hlo_opt/tests/gpu_hlo_pass.hlo --format=hlo --gpu
+          else
+            echo "ERROR: xspace.pb not found. Skipping compute cost."
+            exit 1
+          fi
+
       - name: Checkout juliagmt-google/xla
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Replace with the current SHA of v4.1.1 or later
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
         with:
           repository: juliagmt-google/xla
           path: juliagmt-google-xla
-                
-      - name: Wait For Connection
-        uses: google-ml-infra/actions/ci_connection@main
-        with:
-          halt-dispatch-input: ${{ inputs.halt-for-connection }}
 
-      - name: Run get_device_stats_main
+      - name: Compute the device stats of gpu_hlo_pass.hlo
         run: |
-          echo $XSPACE_PATH
-          bazel run //xla/tools:get_device_stats_main -- --input=$XSPACE_PATH
+          if [ -f "$XSPACE_PATH" ]; then
+            bazel run //xla/tools:get_device_stats_main -- --input="$XSPACE_PATH"
+          else
+            echo "ERROR: xspace.pb not found. Skipping get_device_stats_main."
+            exit 1
+          fi
         working-directory: juliagmt-google-xla
 
-      - name: Upload Artifacts
-        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
+      - name: Upload XSpace
+        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
         with:
-          name: gpu-xla-benchmarks
-          path: results
+          name: gpu-xla-benchmarks-xspace
+          path: results/xspace.pb
     
       # - name: Print machine specs
       #   run: |
