fail hello_world.yml

diff --git a/.github/workflows/hello_world.yml b/.github/workflows/hello_world.yml
--- a/.github/workflows/hello_world.yml
+++ b/.github/workflows/hello_world.yml
@@ -34,8 +34,8 @@ jobs:
           echo "Listing all environment variables:"
           env
           sleep 5
-          echo "Success!"
-          exit 0
+          echo "Fail!"
+          exit 1
   build:
     runs-on: ubuntu-latest
     steps:
